name: LobbySystem
version: 1.0
author: xLixon
main: de.osternachten.lobbyplus.osternachten.listener.listener.LobbyPlus
commands:
    setwarp:
    heal:
    gm:
    kickall:
    perms:
    prefix:
    cc:
    cleanchat:
    wartung: 
    nick:
    build:
    test:
    msg: